# when running in interactive mode without visualization
#
# Set some default verbose
#/control/verbose 2
#/control/saveHistory
#/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 8
#
# Initialize kernel
/run/initialize

/Simulation/setup/configuration 22

/Simulation/output/file HGCalTB_October2018_config22_e+_150GeV.root
/Simulation/generator/momentum 150 GeV
/Simulation/generator/particle e+
/run/beamOn 1000
