# when running in interactive mode without visualization
#
# Set some default verbose
#/control/verbose 2
#/control/saveHistory
#/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 8
#
# Initialize kernel
/run/initialize

/HGCalOctober2018/setup/config 22

/HGCalOctober2018/output/file /Users/tquast/Desktop/HGCalTB_October2018_config22_e+_150GeV.root
/HGCalOctober2018/generator/momentum 150 GeV
/HGCalOctober2018/generator/particle e+
/run/beamOn 1000
